FROM python:3.8.3-alpine3.12

ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apk add --no-cache \
    postgresql-libs \
    gcc \
    musl-dev \
    postgresql-dev

COPY requirements.txt requirements-dev.txt /app/
RUN pip install -r requirements-dev.txt --no-cache-dir

COPY . /app
RUN pip install -e .
